language: python

python:
  - 3.5-dev

services:
  - cassandra

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install liblapack-dev libopenblas-dev libatlas-base-dev gfortran
  - git clone git://github.com/bndl/bndl.git
  - pip install -e "bndl[dev]"

install:
  - pip install pip --upgrade
  - pip install -e .[dev]

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

