language: python

python:
  - 3.5-dev

#services:
#  - cassandra

sudo: required

addons:  
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install liblapack-dev libopenblas-dev libatlas-base-dev gfortran
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz && tar -xvzf apache-cassandra-3.9-bin.tar.gz
  - sudo sh ./apache-cassandra-3.9/bin/cassandra -R
  - git clone git://github.com/bndl/bndl.git
  - pip install -e "bndl[dev]"

install:
  - pip install pip --upgrade
  - pip install -e .[dev]

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

