language: python

python:
  - 3.5-dev

#services:
#  - cassandra

sudo: required

addons:  
  apt:
    packages:
      - oracle-java8-installer

env:
  - CASSANDRA_VERSION=3.9

before_install:
  - sudo apt-get -qq update
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - pip install pip --upgrade
  - git clone git://github.com/bndl/bndl.git
  - sudo apt-get install liblapack-dev libopenblas-dev libatlas-base-dev gfortran
  - pip install -e "bndl[dev]"
  # Workaround for bug #556 in ccm
  - mkdir -p ~/.ccm/repository/3.9
  - wget -qO- http://archive.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz | tar xvz -C ~/.ccm/repository/3.9 --strip-components=1
  - echo "3.9" > ~/.ccm/repository/3.9/0.version.txt

install:
  - pip install -e .[dev]

script: make clean start-cassandra test codestyle stop-cassandra

after_success:
  - bash <(curl -s https://codecov.io/bash)

