language: python

python:
  - 3.5-dev

sudo: required

addons:  
  apt:
    packages:
      - oracle-java8-installer

env:
  - CASSANDRA_VERSION=2.2.8
  - CASSANDRA_VERSION=3.0.10
  - CASSANDRA_VERSION=3.9

before_install:
  - sudo apt-get -qq update
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - pip install pip --upgrade
  - git clone git://github.com/bndl/bndl.git
  - sudo apt-get install liblapack-dev libopenblas-dev libatlas-base-dev gfortran
  - pip install -e "bndl[dev]"
  - pip install "ccm<2.3"

install:
  - pip install -e .[dev]

script: make clean start-cassandra test codestyle stop-cassandra

after_success:
  - bash <(curl -s https://codecov.io/bash)

